#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 05 23:29:00 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Eclipse-Shader-Unstable-0e70ca33.zip
